apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-ingress
spec:
  rules:
  - host: express.com
    http:
      paths:
      - backend:
          serviceName: mongo-express-service
          servicePort: 8081


